# Generated by Django 5.1 on 2024-09-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_tabela_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='nome',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
