# Generated by Django 5.1 on 2024-09-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco_de_dados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estilo',
            new_name='Tabela',
        ),
    ]
